name: Test

on:
  push:
    branches:
      - "use_scss"
      - "main"
      - "release"
  pull_request:
    branches:
      - "use_scss"
      - "main"
      - "release"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Cache Python packages
        id: cache-python
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Format code with black
        run: |
          black --check .

      - name: Test with pytest
        run: |
          pytest
